Error during login test for validUser1: ExpectError: Login for user validUser1 should be successful.

expect(received).toBeTruthy()

Received: false
    at D:\withdraw\PlayWright\src\tests\elements.test.ts:171:13
    at D:\withdraw\PlayWright\src\tests\elements.test.ts:152:7 {
  matcherResult: {
    message: '\x1B[2mexpect(\x1B[22m\x1B[31mreceived\x1B[39m\x1B[2m).\x1B[22mtoBeTruthy\x1B[2m()\x1B[22m\n' +
      '\n' +
      'Received: \x1B[31mfalse\x1B[39m',
    pass: false
  },
  [Symbol(step)]: {
    stepId: 'expect@25',
    category: 'expect',
    title: 'Login for user validUser1 should be successful.',
    params: undefined,
    infectParentStepsWithError: undefined,
    boxedStack: undefined,
    location: {
      file: 'D:\\withdraw\\PlayWright\\src\\tests\\elements.test.ts',
      line: 171,
      column: 13,
      function: undefined
    },
    steps: [],
    complete: [Function: complete],
    endWallTime: 1737648150722,
    error: {
      message: 'Error: Login for user validUser1 should be successful.\n' +
        '\n' +
        '\x1B[2mexpect(\x1B[22m\x1B[31mreceived\x1B[39m\x1B[2m).\x1B[22mtoBeTruthy\x1B[2m()\x1B[22m\n' +
        '\n' +
        'Received: \x1B[31mfalse\x1B[39m',
      stack: 'Error: Login for user validUser1 should be successful.\n' +
        '\n' +
        '\x1B[2mexpect(\x1B[22m\x1B[31mreceived\x1B[39m\x1B[2m).\x1B[22mtoBeTruthy\x1B[2m()\x1B[22m\n' +
        '\n' +
        'Received: \x1B[31mfalse\x1B[39m\n' +
        '    at D:\\withdraw\\PlayWright\\src\\tests\\elements.test.ts:171:13\n' +
        '    at D:\\withdraw\\PlayWright\\src\\tests\\elements.test.ts:152:7',
      cause: undefined,
      matcherResult: [Object]
    }
  }
}
